# Generated by Django 4.1.3 on 2022-11-24 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_bid_alter_auctionlisting_startingbid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='startingbid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='startingbid', to='auctions.bid'),
        ),
    ]
