# Generated by Django 4.1.3 on 2022-11-24 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_auctionlisting_startingbid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='placedbid',
            field=models.IntegerField(),
        ),
    ]
