# Generated by Django 4.1.3 on 2022-11-24 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_alter_bid_placedbid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='placedbid',
            new_name='bid',
        ),
    ]
